rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2

env:
  - RAILS=master AREL=master
  - RAILS=4-1-stable AREL=5-0-stable
  - RAILS=4-0-stable AREL=4-0-stable
  - RAILS=3-2-stable AREL=3-0-stable
  - RAILS=3-1-stable AREL=2-2-stable
  - RAILS=3-0-stable AREL=2-0-stable
